# Generated by Django 4.2.6 on 2023-10-07 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_alter_expense_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
    ]
